In [171]:
# from google.colab import files
# uploaded = files.upload()

# import os, zipfile

# os.makedirs("/root/.kaggle", exist_ok=True)
# for fn in uploaded.keys():
#     os.rename(fn, "/root/.kaggle/kaggle.json")
# os.chmod("/root/.kaggle/kaggle.json", 0o600)

# # Step 2: Download the competition dat
# !kaggle competitions download -c playground-series-s6e5

# #!/bin/bash
# !kaggle datasets download aadigupta1601/f1-strategy-dataset-pit-stop-prediction

# # Step 4: Unzip them
# # Unzip competition
# with zipfile.ZipFile("playground-series-s6e5.zip", "r") as z:
#     z.extractall("playground-series-s6e5")

# # Unzip the simulated roads accident dataset (it will produce those CSVs)
# with zipfile.ZipFile("/content/f1-strategy-dataset-pit-stop-prediction.zip", "r") as z:
#     z.extractall("churndata")

# print("ps6e5 + churndata")

In [172]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [173]:
train_df = pd.read_csv("playground-series-s6e5/train.csv")
test_df = pd.read_csv("playground-series-s6e5/test.csv")

In [174]:
train_df.head()

,id,Driver,Compound,Race,Year,PitStop,LapNumber,Stint,TyreLife,Position,LapTime (s),LapTime_Delta,Cumulative_Degradation,RaceProgress,Position_Change,PitNextLap
0,0,D109,HARD,Canadian Grand Prix,2022,0,50,2,39.0,8,78.491,-7.564,21.019,0.714286,5.0,1.0
1,1,D086,HARD,Dutch Grand Prix,2025,1,27,2,7.0,4,75.095,-32.617,-223.207,0.346154,-3.0,0.0
2,2,ZON,HARD,Austrian Grand Prix,2022,0,59,3,22.0,13,70.945,-7.540,-100.529,0.819444,3.0,1.0
3,3,SPE,MEDIUM,Pre-Season Testing,2023,0,2,1,2.0,7,94.361,-7.324,-7.324,0.076923,0.0,0.0
4,4,D019,HARD,Azerbaijan Grand Prix,2022,1,26,3,6.0,2,107.878,8.965,-14.139,0.361111,3.0,0.0

In [175]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 439140 entries, 0 to 439139
Data columns (total 16 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   id                      439140 non-null  int64
 1   Driver                  439140 non-null  object
 2   Compound                439140 non-null  object
 3   Race                    439140 non-null  object
 4   Year                    439140 non-null  int64
 5   PitStop                 439140 non-null  int64
 6   LapNumber               439140 non-null  int64
 7   Stint                   439140 non-null  int64
 8   TyreLife                439140 non-null  float64
 9   Position                439140 non-null  int64
 10  LapTime (s)             439140 non-null  float64
 11  LapTime_Delta           439140 non-null  float64
 12  Cumulative_Degradation  439140 non-null  float64
 13  RaceProgress            439140 non-null  float64
 14  Position_Change         439140 non-null  float64
 15  PitNextLap              439140 non-null  float64
dtypes: float64(7), int64(6), object(3)
memory usage: 53.6+ MB

In [176]:
data_df =  pd.read_csv("/content/churndata/f1_strategy_dataset_v4.csv")

In [177]:
data_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101371 entries, 0 to 101370
Data columns (total 16 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   Driver                  101371 non-null  object
 1   LapNumber               101371 non-null  int64
 2   Compound                101305 non-null  object
 3   Stint                   101371 non-null  int64
 4   TyreLife                101371 non-null  float64
 5   Position                101371 non-null  int64
 6   LapTime (s)             101371 non-null  float64
 7   Race                    101371 non-null  object
 8   Year                    101371 non-null  int64
 9   LapTime_Delta           101371 non-null  float64
 10  Cumulative_Degradation  101371 non-null  float64
 11  PitStop                 101371 non-null  int64
 12  PitNextLap              101371 non-null  int64
 13  RaceProgress            101371 non-null  float64
 14  Normalized_TyreLife     101371 non-null  float64
 15  Position_Change         101371 non-null  float64
dtypes: float64(7), int64(6), object(3)
memory usage: 12.4+ MB

In [178]:
data_df['Normalized_TyreLife'].describe()

count    101371.000000
mean          0.386521
std           0.259906
min           0.012821
25%           0.172414
50%           0.333333
75%           0.562500
max           1.000000
Name: Normalized_TyreLife, dtype: float64

In [179]:
df = pd.concat([train_df.drop('id', axis=1), data_df.drop('Normalized_TyreLife', axis=1)])

In [180]:
col = train_df['TyreLife']
den = col.max() - col.min()

normalize = (col - col.min()) / den if den != 0 else col * 0
normalize.describe()

count    439140.000000
mean          0.173135
std           0.128965
min           0.000000
25%           0.065789
50%           0.144737
75%           0.250000
max           1.000000
Name: TyreLife, dtype: float64

In [181]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 540511 entries, 0 to 101370
Data columns (total 15 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   Driver                  540511 non-null  object
 1   Compound                540445 non-null  object
 2   Race                    540511 non-null  object
 3   Year                    540511 non-null  int64
 4   PitStop                 540511 non-null  int64
 5   LapNumber               540511 non-null  int64
 6   Stint                   540511 non-null  int64
 7   TyreLife                540511 non-null  float64
 8   Position                540511 non-null  int64
 9   LapTime (s)             540511 non-null  float64
 10  LapTime_Delta           540511 non-null  float64
 11  Cumulative_Degradation  540511 non-null  float64
 12  RaceProgress            540511 non-null  float64
 13  Position_Change         540511 non-null  float64
 14  PitNextLap              540511 non-null  float64
dtypes: float64(7), int64(5), object(3)
memory usage: 66.0+ MB

In [182]:
df['TyreNormalizeLife'] = pd.concat([normalize, data_df['Normalized_TyreLife']])

In [183]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 540511 entries, 0 to 101370
Data columns (total 16 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   Driver                  540511 non-null  object
 1   Compound                540445 non-null  object
 2   Race                    540511 non-null  object
 3   Year                    540511 non-null  int64
 4   PitStop                 540511 non-null  int64
 5   LapNumber               540511 non-null  int64
 6   Stint                   540511 non-null  int64
 7   TyreLife                540511 non-null  float64
 8   Position                540511 non-null  int64
 9   LapTime (s)             540511 non-null  float64
 10  LapTime_Delta           540511 non-null  float64
 11  Cumulative_Degradation  540511 non-null  float64
 12  RaceProgress            540511 non-null  float64
 13  Position_Change         540511 non-null  float64
 14  PitNextLap              540511 non-null  float64
 15  TyreNormalizeLife       540511 non-null  float64
dtypes: float64(8), int64(5), object(3)
memory usage: 70.1+ MB

In [184]:
df1 = df.copy()

In [185]:
df1['Compound'] = df1['Compound'].fillna(df1['Compound'].mode()[0])

In [186]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 540511 entries, 0 to 101370
Data columns (total 16 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   Driver                  540511 non-null  object
 1   Compound                540511 non-null  object
 2   Race                    540511 non-null  object
 3   Year                    540511 non-null  int64
 4   PitStop                 540511 non-null  int64
 5   LapNumber               540511 non-null  int64
 6   Stint                   540511 non-null  int64
 7   TyreLife                540511 non-null  float64
 8   Position                540511 non-null  int64
 9   LapTime (s)             540511 non-null  float64
 10  LapTime_Delta           540511 non-null  float64
 11  Cumulative_Degradation  540511 non-null  float64
 12  RaceProgress            540511 non-null  float64
 13  Position_Change         540511 non-null  float64
 14  PitNextLap              540511 non-null  float64
 15  TyreNormalizeLife       540511 non-null  float64
dtypes: float64(8), int64(5), object(3)
memory usage: 70.1+ MB

In [187]:
df2 = df1.drop('TyreLife', axis=1)

In [188]:
for obj_col in df2.select_dtypes(include='object').columns:
  print(obj_col, ' unique counts = ', df2[obj_col].nunique())
  counts = df2[obj_col].value_counts()
  print(counts[counts > 10].shape, " actual shape ", counts.shape)

Driver  unique counts =  887
(662,)  actual shape  (887,)
Compound  unique counts =  5
(5,)  actual shape  (5,)
Race  unique counts =  28
(28,)  actual shape  (28,)

In [189]:
def target_encode(train_df, test_df, cols, target):
    train_df = train_df.copy()
    test_df = test_df.copy()

    global_mean = train_df[target].mean()

    for col in cols:
        # ensure consistent dtype
        train_df[col] = train_df[col].astype(str)
        test_df[col] = test_df[col].astype(str)

        mapping = train_df.groupby(col)[target].mean()

        # apply mapping
        train_df[col + '_enc'] = train_df[col].map(mapping)
        test_df[col + '_enc'] = test_df[col].map(mapping)

        # handle unseen categories
        test_df[col + '_enc'] = test_df[col + '_enc'].fillna(global_mean)

    return train_df, test_df

In [190]:
cols = ['Driver', 'Race']
target = 'PitNextLap'

df3, test_df = target_encode(df2, test_df, cols, target)

In [191]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 540511 entries, 0 to 101370
Data columns (total 15 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   Driver                  540511 non-null  object
 1   Compound                540511 non-null  object
 2   Race                    540511 non-null  object
 3   Year                    540511 non-null  int64
 4   PitStop                 540511 non-null  int64
 5   LapNumber               540511 non-null  int64
 6   Stint                   540511 non-null  int64
 7   Position                540511 non-null  int64
 8   LapTime (s)             540511 non-null  float64
 9   LapTime_Delta           540511 non-null  float64
 10  Cumulative_Degradation  540511 non-null  float64
 11  RaceProgress            540511 non-null  float64
 12  Position_Change         540511 non-null  float64
 13  PitNextLap              540511 non-null  float64
 14  TyreNormalizeLife       540511 non-null  float64
dtypes: float64(7), int64(5), object(3)
memory usage: 66.0+ MB

In [192]:
df3[df3['Driver'] == 'IDE'].head()

,Driver,Compound,Race,Year,PitStop,LapNumber,Stint,Position,LapTime (s),LapTime_Delta,Cumulative_Degradation,RaceProgress,Position_Change,PitNextLap,TyreNormalizeLife,Driver_enc,Race_enc
46,IDE,HARD,French Grand Prix,2022,1,39,2,7,97.987,27.924,-45.553,0.541667,2.0,0.0,0.236842,0.212604,0.272639
290,IDE,INTERMEDIATE,Canadian Grand Prix,2024,0,27,2,15,92.633,0.000,-26.099,0.380282,-3.0,1.0,0.184211,0.212604,0.156191
630,IDE,SOFT,Spanish Grand Prix,2023,0,7,1,6,80.834,-0.130,-3.769,0.098592,2.0,0.0,0.105263,0.212604,0.316795
1710,IDE,MEDIUM,Abu Dhabi Grand Prix,2025,0,54,3,17,87.874,6.878,-4.063,0.710526,0.0,0.0,0.131579,0.212604,0.163000
1801,IDE,MEDIUM,United States Grand Prix,2024,0,25,1,11,100.821,1.631,-34.970,0.324675,8.0,0.0,0.315789,0.212604,0.128975

In [193]:
df4 = df3.drop(['Driver', 'Race'], axis=1)

In [194]:
df4.head()

,Compound,Year,PitStop,LapNumber,Stint,Position,LapTime (s),LapTime_Delta,Cumulative_Degradation,RaceProgress,Position_Change,PitNextLap,TyreNormalizeLife,Driver_enc,Race_enc
0,HARD,2022,0,50,2,8,78.491,-7.564,21.019,0.714286,5.0,1.0,0.500000,0.200971,0.156191
1,HARD,2025,1,27,2,4,75.095,-32.617,-223.207,0.346154,-3.0,0.0,0.078947,0.191816,0.184453
2,HARD,2022,0,59,3,13,70.945,-7.540,-100.529,0.819444,3.0,1.0,0.276316,0.228669,0.197016
3,MEDIUM,2023,0,2,1,7,94.361,-7.324,-7.324,0.076923,0.0,0.0,0.013158,0.194134,0.145613
4,HARD,2022,1,26,3,2,107.878,8.965,-14.139,0.361111,3.0,0.0,0.065789,0.192308,0.231349

In [195]:
df4.info()

<class 'pandas.core.frame.DataFrame'>
Index: 540511 entries, 0 to 101370
Data columns (total 15 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   Compound                540511 non-null  object
 1   Year                    540511 non-null  int64
 2   PitStop                 540511 non-null  int64
 3   LapNumber               540511 non-null  int64
 4   Stint                   540511 non-null  int64
 5   Position                540511 non-null  int64
 6   LapTime (s)             540511 non-null  float64
 7   LapTime_Delta           540511 non-null  float64
 8   Cumulative_Degradation  540511 non-null  float64
 9   RaceProgress            540511 non-null  float64
 10  Position_Change         540511 non-null  float64
 11  PitNextLap              540511 non-null  float64
 12  TyreNormalizeLife       540511 non-null  float64
 13  Driver_enc              540511 non-null  float64
 14  Race_enc                540511 non-null  float64
dtypes: float64(9), int64(5), object(1)
memory usage: 66.0+ MB

In [196]:
df4['Position_Change'].astype('int').unique()

array([  5,  -3,   3,   0,  -9,   4,   6,  -1,  -2,   2,   7,  -4,   1,
        -8,   8,  -5,   9,  11,  14,  -6, -10, -11,  -7,  10,  13, -16,
       -12, -14, -13, -15,  15,  12,  17, -18,  16, -17,  18])

In [197]:
one_hot_cols = ['Year', 'Compound']

In [198]:
df5 = pd.get_dummies(df4, columns=one_hot_cols)

In [199]:
df5.head()

,PitStop,LapNumber,Stint,Position,LapTime (s),LapTime_Delta,Cumulative_Degradation,RaceProgress,Position_Change,PitNextLap,...,Race_enc,Year_2022,Year_2023,Year_2024,Year_2025,Compound_HARD,Compound_INTERMEDIATE,Compound_MEDIUM,Compound_SOFT,Compound_WET
0,0,50,2,8,78.491,-7.564,21.019,0.714286,5.0,1.0,...,0.156191,True,False,False,False,True,False,False,False,False
1,1,27,2,4,75.095,-32.617,-223.207,0.346154,-3.0,0.0,...,0.184453,False,False,False,True,True,False,False,False,False
2,0,59,3,13,70.945,-7.540,-100.529,0.819444,3.0,1.0,...,0.197016,True,False,False,False,True,False,False,False,False
3,0,2,1,7,94.361,-7.324,-7.324,0.076923,0.0,0.0,...,0.145613,False,True,False,False,False,False,True,False,False
4,1,26,3,2,107.878,8.965,-14.139,0.361111,3.0,0.0,...,0.231349,True,False,False,False,True,False,False,False,False

In [200]:
df5.info()

<class 'pandas.core.frame.DataFrame'>
Index: 540511 entries, 0 to 101370
Data columns (total 22 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   PitStop                 540511 non-null  int64
 1   LapNumber               540511 non-null  int64
 2   Stint                   540511 non-null  int64
 3   Position                540511 non-null  int64
 4   LapTime (s)             540511 non-null  float64
 5   LapTime_Delta           540511 non-null  float64
 6   Cumulative_Degradation  540511 non-null  float64
 7   RaceProgress            540511 non-null  float64
 8   Position_Change         540511 non-null  float64
 9   PitNextLap              540511 non-null  float64
 10  TyreNormalizeLife       540511 non-null  float64
 11  Driver_enc              540511 non-null  float64
 12  Race_enc                540511 non-null  float64
 13  Year_2022               540511 non-null  bool
 14  Year_2023               540511 non-null  bool
 15  Year_2024               540511 non-null  bool
 16  Year_2025               540511 non-null  bool
 17  Compound_HARD           540511 non-null  bool
 18  Compound_INTERMEDIATE   540511 non-null  bool
 19  Compound_MEDIUM         540511 non-null  bool
 20  Compound_SOFT           540511 non-null  bool
 21  Compound_WET            540511 non-null  bool
dtypes: bool(9), float64(9), int64(4)
memory usage: 62.4 MB

In [201]:
bool_cols = df5.select_dtypes(include='bool').columns
df5[bool_cols] = df5[bool_cols].astype('int8')
df5['PitNextLap'] = df5['PitNextLap'].astype('int8')

In [202]:
df5.info()

<class 'pandas.core.frame.DataFrame'>
Index: 540511 entries, 0 to 101370
Data columns (total 22 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   PitStop                 540511 non-null  int64
 1   LapNumber               540511 non-null  int64
 2   Stint                   540511 non-null  int64
 3   Position                540511 non-null  int64
 4   LapTime (s)             540511 non-null  float64
 5   LapTime_Delta           540511 non-null  float64
 6   Cumulative_Degradation  540511 non-null  float64
 7   RaceProgress            540511 non-null  float64
 8   Position_Change         540511 non-null  float64
 9   PitNextLap              540511 non-null  int8
 10  TyreNormalizeLife       540511 non-null  float64
 11  Driver_enc              540511 non-null  float64
 12  Race_enc                540511 non-null  float64
 13  Year_2022               540511 non-null  int8
 14  Year_2023               540511 non-null  int8
 15  Year_2024               540511 non-null  int8
 16  Year_2025               540511 non-null  int8
 17  Compound_HARD           540511 non-null  int8
 18  Compound_INTERMEDIATE   540511 non-null  int8
 19  Compound_MEDIUM         540511 non-null  int8
 20  Compound_SOFT           540511 non-null  int8
 21  Compound_WET            540511 non-null  int8
dtypes: float64(8), int64(4), int8(10)
memory usage: 58.8 MB

In [203]:
df5.head()

,PitStop,LapNumber,Stint,Position,LapTime (s),LapTime_Delta,Cumulative_Degradation,RaceProgress,Position_Change,PitNextLap,...,Race_enc,Year_2022,Year_2023,Year_2024,Year_2025,Compound_HARD,Compound_INTERMEDIATE,Compound_MEDIUM,Compound_SOFT,Compound_WET
0,0,50,2,8,78.491,-7.564,21.019,0.714286,5.0,1,...,0.156191,1,0,0,0,1,0,0,0,0
1,1,27,2,4,75.095,-32.617,-223.207,0.346154,-3.0,0,...,0.184453,0,0,0,1,1,0,0,0,0
2,0,59,3,13,70.945,-7.540,-100.529,0.819444,3.0,1,...,0.197016,1,0,0,0,1,0,0,0,0
3,0,2,1,7,94.361,-7.324,-7.324,0.076923,0.0,0,...,0.145613,0,1,0,0,0,0,1,0,0
4,1,26,3,2,107.878,8.965,-14.139,0.361111,3.0,0,...,0.231349,1,0,0,0,1,0,0,0,0

In [204]:
import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_auc_score

In [205]:
X_train, X_test, y_train, y_test = train_test_split(df5.drop('PitNextLap', axis=1), df5['PitNextLap'], test_size=0.15)

In [226]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 459434 entries, 338525 to 7836
Data columns (total 21 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   PitStop                 459434 non-null  int64
 1   LapNumber               459434 non-null  int64
 2   Stint                   459434 non-null  int64
 3   Position                459434 non-null  int64
 4   LapTime (s)             459434 non-null  float64
 5   LapTime_Delta           459434 non-null  float64
 6   Cumulative_Degradation  459434 non-null  float64
 7   RaceProgress            459434 non-null  float64
 8   Position_Change         459434 non-null  float64
 9   TyreNormalizeLife       459434 non-null  float64
 10  Driver_enc              459434 non-null  float64
 11  Race_enc                459434 non-null  float64
 12  Year_2022               459434 non-null  int8
 13  Year_2023               459434 non-null  int8
 14  Year_2024               459434 non-null  int8
 15  Year_2025               459434 non-null  int8
 16  Compound_HARD           459434 non-null  int8
 17  Compound_INTERMEDIATE   459434 non-null  int8
 18  Compound_MEDIUM         459434 non-null  int8
 19  Compound_SOFT           459434 non-null  int8
 20  Compound_WET            459434 non-null  int8
dtypes: float64(8), int64(4), int8(9)
memory usage: 49.5 MB

In [207]:
X_train.shape, y_train.shape

((459434, 21), (459434,))

In [208]:
xgb_model = xgb.XGBClassifier()
xgb_model.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=None,
              n_jobs=None, num_parallel_tree=None, ...)

In [210]:
xgb_model.score(X_test, y_test)

0.8940636678712829

In [211]:
roc_auc_score(y_test, xgb_model.predict_proba(X_test)[:, 1])

np.float64(0.944918071488174)

In [212]:
test_df.head()

,id,Driver,Compound,Race,Year,PitStop,LapNumber,Stint,TyreLife,Position,LapTime (s),LapTime_Delta,Cumulative_Degradation,RaceProgress,Position_Change,Driver_enc,Race_enc
0,439140,D119,MEDIUM,British Grand Prix,2023,0,21,1,21.0,4,93.387,0.280,-4.984,0.403846,0.0,0.182292,0.151095
1,439141,VER,MEDIUM,Abu Dhabi Grand Prix,2023,0,24,1,24.0,1,90.867,-0.129,-1.990,0.413793,0.0,0.286194,0.163000
2,439142,D270,MEDIUM,British Grand Prix,2023,0,24,1,24.0,11,92.871,0.041,-8.842,0.461538,0.0,0.121622,0.151095
3,439143,D112,SOFT,São Paulo Grand Prix,2024,0,6,2,4.0,15,94.967,-19.741,8.250,0.077922,1.0,0.198847,0.257902
4,439144,AND,HARD,United States Grand Prix,2024,0,52,2,29.0,12,99.112,0.930,-20.848,0.722222,7.0,0.197125,0.128975

In [213]:
test_df1 = pd.get_dummies(test_df, columns=one_hot_cols)

In [214]:
test_df1.head()

,id,Driver,Race,PitStop,LapNumber,Stint,TyreLife,Position,LapTime (s),LapTime_Delta,...,Race_enc,Year_2022,Year_2023,Year_2024,Year_2025,Compound_HARD,Compound_INTERMEDIATE,Compound_MEDIUM,Compound_SOFT,Compound_WET
0,439140,D119,British Grand Prix,0,21,1,21.0,4,93.387,0.280,...,0.151095,False,True,False,False,False,False,True,False,False
1,439141,VER,Abu Dhabi Grand Prix,0,24,1,24.0,1,90.867,-0.129,...,0.163000,False,True,False,False,False,False,True,False,False
2,439142,D270,British Grand Prix,0,24,1,24.0,11,92.871,0.041,...,0.151095,False,True,False,False,False,False,True,False,False
3,439143,D112,São Paulo Grand Prix,0,6,2,4.0,15,94.967,-19.741,...,0.257902,False,False,True,False,False,False,False,True,False
4,439144,AND,United States Grand Prix,0,52,2,29.0,12,99.112,0.930,...,0.128975,False,False,True,False,True,False,False,False,False

In [219]:
test_df2 = test_df1.copy()

In [220]:
train_min = train_df['TyreLife'].min()
train_max = train_df['TyreLife'].max()

test_df2['TyreNormalizeLife'] = (
    test_df2['TyreLife'] - train_min
) / (train_max - train_min)

In [221]:
id_col, final_test_df = test_df2['id'], test_df2.drop(['Driver', 'Race', 'id', 'TyreLife'], axis=1)

In [222]:
final_test_df.shape

(188165, 21)

In [231]:
print("Only in train:", set(X_train.columns) - set(final_test_df.columns))
print("Only in test :", set(final_test_df.columns) - set(X_train.columns))

Only in train: set()
Only in test : set()

In [233]:
final_test_df = final_test_df[X_train.columns]

In [234]:
print(list(X_train.columns) == list(final_test_df.columns))  # must be True

True

In [235]:
xgb_model.predict_proba(final_test_df)[:, 1]

array([3.9528417e-03, 8.1638055e-04, 7.2928052e-03, ..., 7.9702896e-01,
       8.6163557e-01, 1.8135464e-02], dtype=float32)

In [236]:
sub_df = pd.DataFrame({
    'id': id_col,
    'PitNextLap': xgb_model.predict_proba(final_test_df)[:, 1]
})

In [237]:
sub_df.to_csv('submission.csv', index=False)

(188165, 21)